### PR TITLE
Upgrade to latest Electron, many dependencies, and added Qlab5 Module

### PR DESCRIPTION
**Pull request by markvesterskov**
Upgraded to latest electron version
Updated many dependencies to newer (if not newest) versions
Added option to show armed cue (selected cue in Qlab) when no VT is playing
Added option to change VT Timer color to a warning and a danger state (so it turns red and yellow like the progress bar)
Added Qlab5 module
Fixed typo in Qlab4 module (color blue)
Removed analytics, as they are being depreciated on less than 14 days anyways
Updated design so window is now resizable
Added voice countdown option
Updated webserver design slightly
Made Dark Mode switchable in settings instead of dictated by system setting

### CODE REVIEW

**Comment by DrewLX** [comment]
I can't currently get this to run on my machine. What node version are you using?

I think some of the dependancy updates may have broken the build? I get some errors around Font Awesome, element-plus and something called howler. If I use node LTS I get stuck on the crypto issue facing more recent electron releases.

**Comment by markvesterskov** [comment]
Lets see if we cant get that sorted. Node v14.21.2, installing using yarn 1.22.19 works for me here 🥳

**Comment by DrewLX** [comment]
Ah yes, likely due to the old node version. If I set nvm to use that then my only issue seems to be font awesome 6.4 - which I think changed some of how it authenticates

**Comment by markvesterskov** [comment]
I'll have a look at upgrading to node 16. I'll be back.

**Comment by markvesterskov** [comment]
@DrewLX Give it a shot now. Installs and builds fine here using node 16.18.0, npm 8.19.2 and installing via npm.

`npm install
npm run electron:serve`

**Comment by DrewLX** [comment]
Yup, now runs/builds! Some of the work is looking excellent and all the progress I keep wanting to make. However it looks like a theme file link may be broken: 
image

**Comment by markvesterskov** [comment]
Nice! What theme file link do you think is missing?

**Comment by DrewLX** [comment]
Comparing to release, the background should be #222 and the 'highlight' colour should be Alteka green #6ab42f
image

**Comment by markvesterskov** [comment]
Ah gotcha. The background color i changed to full black to make the counter easier to key/fill using something like a Barco E2 or an analog way switcher. With full black its possible to just Luma key it in.

I'll look at the green color, probably missing after upgrading elements-plus.

**Comment by DrewLX** [comment]
I'm currently building at Montreux Jazz Festival, but once we're build I'll have 2-3 weeks of down time where I can properly work through this PR and ensure it matches the Alteka styling

**Comment by DrewLX** [comment]
Thanks. I think the black for show is sensible choice, but the control UI should look like the other Alteka apps

**Comment by markvesterskov** [comment]
> Thanks. I think the black for show is sensible choice, but the control UI should look like the other Alteka apps

Gotcha. Just implemented that, and fixed the primary color.

**Comment by DrewLX** [comment]
Sweet, looking much better. 

I'd like @canoemoose to have a look before we merge in, but I think with only a few minor things we could actually put this out as 1.0.0

**Comment by DrewLX** [comment]
Merging in - I'm going to spend the weekend tweaking and tidying up a few bits.... and adding another little feature before. Aiming to release as 1.0.0 sometime next week.

**Pull request merged**
